### ISSUE TITLE
Support lists in configuration

### ISSUE THREAD

**Issue by mcbanderson** [cloudmitigator/reflex-cli#100]
We currently only support regular key-value pairs, and map/dict values. We should support list values as well.

How to reproduce:
`reflex.yaml`
```
rules:
  aws:
  - my-rule:
      configuration:
        foo:
          - bar
          - baz
      version: latest
```
`reflex build`

Expected output:
`my-rule.tf`
```
module "my-rule" {
  source            = "git::https://github.com/cloudmitigator/my-rule.git?ref=latest"
  sns_topic_arn     = module.central-sns-topic.arn
  reflex_kms_key_id = module.reflex-kms-key.key_id
  foo = [
    "bar",
    "baz",
  ]
}
```

Actual output:
`my-rule.tf`
```
module "my-rule" {
  source            = "git::https://github.com/cloudmitigator/my-rule.git?ref=latest"
  sns_topic_arn     = module.central-sns-topic.arn
  reflex_kms_key_id = module.reflex-kms-key.key_id
  foo = [&#39;bar&#39;, &#39;baz&#39;]
}
```
