### ISSUE TITLE
`upgrade` command prompts about overwriting file if no changes are requested

### ISSUE THREAD

**Issue by mcbanderson** [cloudmitigator/reflex-cli#105]
If you run `reflex upgrade`, but then respond `no` to upgrading all rules, you'll still get prompted about overwriting the config file even though no changes are required.

version: reflex, version 0.11.5

How to reproduce:
`reflex.yaml`
```
rules:
  aws:
  - enforce-s3-encryption:
      configuration:
        mode: detect
      version: v0.4.2
```

Then run `reflex upgrade`, and respond `n`.
