### ISSUE TITLE
`reflex build` doesn't correctly output `environment_variable_map`

### ISSUE THREAD

**Issue by mcbanderson** [cloudmitigator/reflex-cli#89]
`reflex build` doesn't correctly build `reflex-aws-*.tf` files when `environment_variable_map` is specified in `reflex.yaml`.

**Steps to reproduce:**
`reflex.yaml`
```
rules:
- reflex-aws-rule:
    configuration:
    - environment_variable_map:
        FIRST_KEY: KEY_VALUE_1
        SECOND_KEY: KEY_VALUE_2
    version: v0.0.1
```

Then run `reflex build`.

**Expected output:**
```
module "reflex-aws-rule" {
  ...

  environment_variable_map = {
    FIRST_KEY: "KEY_VALUE_1",
    SECOND_KEY: "KEY_VALUE_2"
  }
}
```

**Actual output:**
```
module "reflex-aws-rule" {
  ...

  environment_variable_map = "{&#39;FIRST_KEY&#39;: KEY_VALUE_1, &#39;SECOND_KEY&#39;: KEY_VALUE_2}"
}
```
